/**
 * Import will remove at compile time
 */

import type { BuildOptions, BuildResult } from 'esbuild';
import type { EntryPoints, transpileFileInterface } from '@services/interfaces/transpiler.interface';

/**
 * Imports
 */

import { cwd } from 'process';
import { build } from 'esbuild';
import { xJetError } from '@errors/xjet.error';

/**
 * Default build options for esbuild bundler in RemoteX framework.
 *
 * These options are used to configure how esbuild processes and bundles the TypeScript
 * files for the RemoteX testing framework.
 *
 * @public
 * @category Configuration
 */

export const defaultBuildOptions: BuildOptions = {
    write: false,
    bundle: true,
    minify: true,
    format: 'cjs',
    target: 'esnext',
    platform: 'node',
    sourcemap: true,
    sourcesContent: true,
    preserveSymlinks: true
};

/**
 * Extracts the source map from the provided data string and returns the modified code and source map separately.
 *
 * This function searches for the inline source map in the data string using a regular expression, removes the
 * source map comment from the data string, and returns an object containing the code without the source map
 * comment and the extracted source map.
 *
 * @param dataString - The string containing the transpiled code with an inline source map.
 * @returns An object containing the modified code without the source map comment and the extracted source map.
 * @throws Error -Throws an error if the source map URL is not found in the data string.
 *
 * @public
 */

export function extractSourceMap(dataString: string): transpileFileInterface {
    const sourceMapRegex = /\/\/# sourceMappingURL=data:application\/json;base64,([^'"\s]+)/;
    const match = dataString.match(sourceMapRegex);

    if (!match || !match[1]) {
        throw new xJetError('Source map URL not found in the output.');
    }

    const sourceMap = atob(match[1]);
    const codeWithoutSourceMap = dataString.replace(sourceMapRegex, '');

    return { code: codeWithoutSourceMap, sourceMap };
}

/**
 * Transpiles a TypeScript file and extracts the source map.
 *
 * This function uses esbuild to transpile the specified TypeScript file based on provided build options,
 * and then extracts the source map from the transpiled code.
 *
 * @param filePath - The path to the TypeScript file to be transpiled.
 * @param buildOptions - Optional build options to override the default build options.
 * @returns A promise that resolves to an object containing the transpiled code and the extracted source map.
 * @throws Error - Throws an error if the build process fails or the source map extraction fails.
 *
 * @public
 * @category Services
 */

export async function transpileFile(filePath: string, buildOptions: BuildOptions = {}): Promise<transpileFileInterface> {
    const options: BuildOptions = {
        absWorkingDir: cwd(),
        ...defaultBuildOptions,
        ...buildOptions,
        entryPoints: [ filePath ]
    };

    const result = await build(options);
    const fileContent = result.outputFiles?.pop()?.text ?? '';

    // Retrieve the transpiled code from the build output.
    return extractSourceMap(fileContent);
}

/**
 * Transpiles an array of TypeScript or JavaScript files to JavaScript using esbuild.
 *
 * This function takes an array of file paths and transpiles them using esbuild, with
 * customizable build options. By default, the files are outputted to a temporary directory (`outdir: 'temp'`).
 * The build output is formatted as ECMAScript modules (`format: 'esm'`), targeting modern JavaScript (`target: 'esnext'`),
 * and intended for the browser platform. Sourcemaps are generated as external files.
 *
 * @param entryPoints - An array of file paths that need to be transpiled.
 * @param buildOptions - Optional esbuild `BuildOptions` to override or extend the default build settings.
 * @returns A promise that resolves to a `BuildResult`, which includes details about the transpilation process, such as output files, warnings, errors, etc.
 *
 * @example
 * // Example usage of transpileFiles function:
 * const files = ['src/index.ts', 'src/app.ts'];
 * const buildResult = await transpileFiles(files);
 *
 * // Custom build options example
 * const customOptions = { minify: true, sourcemap: 'inline' };
 * const buildResult = await transpileFiles(files, customOptions);
 *
 * @remarks
 * - This function uses the esbuild `build` API with output files kept in-memory unless specified otherwise.
 * - The default output directory is set to `'temp'`, but can be changed by providing custom `BuildOptions`.
 * - The build targets ECMAScript modules (`format: 'esm'`) and supports modern JavaScript (`target: 'esnext'`).
 * - The `platform` is set to `'browser'`, making the output suitable for browser environments.
 * - External sourcemaps are generated by default, but this behavior can be changed via the `sourcemap` option.
 * - The `absWorkingDir` is set to the current working directory (`cwd()`), but can be overridden through the `buildOptions` parameter.
 *
 * @see https://esbuild.github.io/api/#build-options for more information on esbuild's `BuildOptions`.
 */

export async function transpileFiles(entryPoints: EntryPoints, buildOptions: BuildOptions = {}): Promise<BuildResult> {
    const options: BuildOptions = {
        absWorkingDir: cwd(),
        ...defaultBuildOptions,
        ...buildOptions,
        format: 'cjs',
        target: 'esnext',
        platform: 'browser',
        sourcemap: 'external',
        entryPoints: entryPoints
    };

    return await build(options);
}
